update

diff --git a/.github/workflows/enable-disable-scheduler-rule.yml b/.github/workflows/enable-disable-scheduler-rule.yml
--- a/.github/workflows/enable-disable-scheduler-rule.yml
+++ b/.github/workflows/enable-disable-scheduler-rule.yml
@@ -71,4 +71,4 @@ jobs:
         run: |
           echo "❌ FAILED to update scheduler." >> $GITHUB_STEP_SUMMARY
           echo "--- Error Log ---"
-          cat update_error.log || echo "No error log found."
+          cat update_error.log || echo "No error log found." >> $GITHUB_STEP_SUMMARY
