28888

diff --git a/.github/workflows/EventBridge_state_Toggle.yaml b/.github/workflows/EventBridge_state_Toggle.yaml
--- a/.github/workflows/EventBridge_state_Toggle.yaml
+++ b/.github/workflows/EventBridge_state_Toggle.yaml
@@ -10,14 +10,14 @@ on:
         options:
           - dev01
           - dev02
-      batch_name:
+      schedule_name:
         description: "Batch Rule Name (without prefix)"
         required: true
         type: choice
         options:
           - enable-disable-test
           - enable-disable
-      state:
+      schedule_state:
         description: "Desired state (ENABLED or DISABLED)"
         required: true
         type: choice
@@ -40,57 +40,48 @@ jobs:
           role-to-assume: arn:aws:iam::022269452713:role/AssumeRoleGHAction
           aws-region: ap-southeast-1
 
-      - name: Set environment variables
-        run: |
-          echo "schedule_name=td-${{ inputs.env }}-${{ inputs.batch_name }}" >> $GITHUB_ENV
-          echo "desired_state=${{ inputs.state }}" >> $GITHUB_ENV
-
-      - name: Validate and update Scheduler State
+      - name: Check current Scheduler State
         id: validate_schedule
         run: |
-          set +e
-          result=$(aws scheduler get-schedule --name "$schedule_name" 2>&1)
-          status=$?
+          schedule_full_name=td-${{ inputs.env }}-${{ inputs.schedule_name }}
+          echo "schedule_full_name=$schedule_full_name" >> $GITHUB_OUTPUT
 
-          # Check existence
-          if echo "$result" | grep -q "ResourceNotFoundException"; then
-            echo "Scheduler '$schedule_name' does not exist." >> $GITHUB_STEP_SUMMARY
-            echo "$result"
-            exit 1
-          fi
-
-          # Check error
-          if [ "$status" -ne "0" ]; then
-            echo "Error: Failed to retrieve the scheduler \`$schedule_name\`!" >> $GITHUB_STEP_SUMMARY
+          response_get=$(aws scheduler get-schedule --name "$schedule_full_name" 2>&1) || {
+            echo "Error: Failed to retrieve the scheduler $schedule_full_name!" >> $GITHUB_STEP_SUMMARY
             echo '```' >> $GITHUB_STEP_SUMMARY
-            echo "$result" >> $GITHUB_STEP_SUMMARY
+            echo "$response_get" >> $GITHUB_STEP_SUMMARY
             echo '```' >> $GITHUB_STEP_SUMMARY
             exit 1
-          fi
+          }
 
           # Check current state
-          current_state=$(echo "$result" | jq -r '.State')
-          if [ "$current_state" = "$desired_state" ]; then
-            echo "Scheduler \`$schedule_name\` is already in desired state:\`$current_state\`." >> $GITHUB_STEP_SUMMARY
+          current_state=$(echo "$response_get" | jq -r '.State') || {
+            echo "Error: Unable to parse state from response!" >> $GITHUB_STEP_SUMMARY
             exit 1
+          }
+          if [ "$current_state" = "${{ inputs.schedule_state }}" ]; then
+            echo "Scheduler \`$schedule_full_name\` is already in desired state:\`$current_state\`." >> $GITHUB_STEP_SUMMARY
+            echo "matched=true" >> $GITHUB_OUTPUT
+            exit 0
+          else
+            echo "matched=false" >> $GITHUB_OUTPUT
           fi
-          encoded=$(echo "$result" | base64 -w 0)
-          echo "result=$encoded" >> $GITHUB_OUTPUT
+
+          echo "schedule_json=$(echo "$response_get" | base64 -w 0)" >> $GITHUB_OUTPUT
       - name: Validate and update Scheduler State
+        if: steps.validate_schedule.outputs.matched == 'false'
         run: |
-          set +e
           # Removing read-only fields
-          json_input=$(echo "${{ steps.validate_schedule.outputs.result }}" | base64 -d)
-          json_input=$(echo "$raw_json" | jq -c 'del(.Arn, .CreationDate, .LastModificationDate)')
+          json_decode=$(echo "${{ steps.validate_schedule.outputs.schedule_json }}" | base64 -d)
+          json_input=$(echo "$json_decode" | jq -c 'del(.Arn, .CreationDate, .LastModificationDate)')
 
           # Update state
-          output=$(aws scheduler update-schedule --cli-input-json "$json_input" --state "$desired_state" 2>&1)
-          status=$?
-          if [ "$status" -ne 0 ]; then
-            echo "Error: Failed to update the scheduler \`$schedule_name\`!" >> $GITHUB_STEP_SUMMARY
+          response_update=$(aws scheduler update-schedule --cli-input-json "$json_input" --state "${{ inputs.schedule_state }}" 2>&1) || {
+            echo "Error: Failed to update the scheduler ${{ steps.validate_schedule.outputs.schedule_full_name }}" >> $GITHUB_STEP_SUMMARY
             echo '```' >> $GITHUB_STEP_SUMMARY
-            echo "$output" >> $GITHUB_STEP_SUMMARY
+            echo "$response_update" >> $GITHUB_STEP_SUMMARY
             echo '```' >> $GITHUB_STEP_SUMMARY
             exit 1
-          fi
-          echo "Successfully updated scheduler \`$schedule_name\` to \`$desired_state\`." >> $GITHUB_STEP_SUMMARY
+          }
+
+          echo "Successfully updated scheduler ${{ steps.validate_schedule.outputs.schedule_full_name }} to ${{ inputs.schedule_state }}." >> $GITHUB_STEP_SUMMARY
