update

diff --git a/.github/workflows/EventBridge_state_Toggle.yaml b/.github/workflows/EventBridge_state_Toggle.yaml
--- a/.github/workflows/EventBridge_state_Toggle.yaml
+++ b/.github/workflows/EventBridge_state_Toggle.yaml
@@ -48,17 +48,18 @@ jobs:
       - name: Fetch scheduler info and handle logic
         id: update_schedule_state
         run: |
-          RAW_JSON=$(aws scheduler get-schedule --name "$SCHEDULER_NAME")
+          result=$(aws scheduler get-schedule --name "$SCHEDULER_NAME" 2>&1)
+          status=$?
           # Check exist
-          if echo "$RAW_JSON" | grep -q "ResourceNotFoundException"; then
-            echo "Scheduler \`$SCHEDULER_NAME\` does not exist." >> $GITHUB_STEP_SUMMARY
-            echo "not_found=true" >> "$GITHUB_OUTPUT"
+          if [ "$status" -ne 0 ]; then
+            echo "Error: Lỗi khi lấy thông tin schedule từ AWS" >> $GITHUB_STEP_SUMMARY
+            echo '```' >> $GITHUB_STEP_SUMMARY
+            echo "$result" >> $GITHUB_STEP_SUMMARY
+            echo '```' >> $GITHUB_STEP_SUMMARY
             exit 1
           fi
 
-          SCHEDULER_JSON=$(echo "$RAW_JSON" | jq '.')
-
-          CURRENT_STATE=$(echo "$SCHEDULER_JSON" | jq -r '.State')
+          CURRENT_STATE=$(echo "$result" | jq -r '.State')
           # Check current state
           if [ "$CURRENT_STATE" = "$DESIRED_STATE" ]; then
             echo "Scheduler \`$SCHEDULER_NAME\` is already in desired state: $CURRENT_STATE." >> $GITHUB_STEP_SUMMARY
@@ -66,16 +67,20 @@ jobs:
           fi
 
           # Prepare new JSON for update
-          JSON_INPUT=$(echo "$SCHEDULER_JSON" | jq --arg state "$DESIRED_STATE" '
+          result=$(echo "$result" | jq '.')
+          json_input=$(echo "$result" | jq --arg state "$DESIRED_STATE" '
             .State = $state
             | del(.Arn, .CreationDate, .LastModificationDate)
           ')
 
-          aws scheduler update-schedule --cli-input-json "$JSON_INPUT"
-
+          output=$(aws scheduler update-schedule --cli-input-json "$json_input" --state "$DESIRED_STATE" 2>&1)
+          status=$?
+          if [ "$status" -ne 0 ]; then
+            echo "Error: Lỗi khi cập nhật thông tin schedule trên AWS" >> $GITHUB_STEP_SUMMARY
+            echo '```' >> $GITHUB_STEP_SUMMARY
+            echo "$output" >> $GITHUB_STEP_SUMMARY
+            echo '```' >> $GITHUB_STEP_SUMMARY
+            exit 1
+          fi
           echo "Successfully updated scheduler \`$SCHEDULER_NAME\` to \`$DESIRED_STATE\`." >> $GITHUB_STEP_SUMMARY
 
-      - name: Handle unexpected error
-        if: failure() && steps.update_schedule_state.outputs.not_found != 'true'
-        run: |
-          echo "An unexpected error occurred during the workflow execution." >> $GITHUB_STEP_SUMMARY
