update

diff --git a/.github/workflows/trieulv-ver2.yaml b/.github/workflows/trieulv-ver2.yaml
--- a/.github/workflows/trieulv-ver2.yaml
+++ b/.github/workflows/trieulv-ver2.yaml
@@ -105,25 +105,25 @@ jobs:
       - name: Process Athena query results
         id: processing_query
         run: |
-                query_result=$(aws athena get-query-results --query-execution-id $query_execution_id)
-                processed_result=$(echo "$query_result" | jq -c '.ResultSet.Rows
-                | .[1:3] # Lấy phần tử từ index 1 đến (nhưng không bao gồm) index 3
-                | map({
-                datetime: .Data[0].VarCharValue,
-                action: .Data[1].VarCharValue,
-                uri: .Data[2].VarCharValue,
-                terminatingruleid: .Data[3].VarCharValue,
-                country: .Data[4].VarCharValue,
-                ruleid: .Data[5].VarCharValue,
-                header: .Data[6].VarCharValue,
-                terminatingrulematchdetails: .Data[7].VarCharValue,
-                args: .Data[8].VarCharValue
+          query_result=$(aws athena get-query-results --query-execution-id $query_execution_id)
+          processed_result=$(echo "$query_result" | jq -c '.ResultSet.Rows
+              | .[1:]
+              | map({
+                  datetime: .Data[0].VarCharValue,
+                  action: .Data[1].VarCharValue,
+                  uri: .Data[2].VarCharValue,
+                  terminatingruleid: .Data[3].VarCharValue,
+                  country: .Data[4].VarCharValue,
+                  ruleid: .Data[5].VarCharValue,
+                  header: .Data[6].VarCharValue,
+                  terminatingrulematchdetails: .Data[7].VarCharValue,
+                  args: .Data[8].VarCharValue
                 })
-                | map(@json)
-                | join("\n")' \
-                | sed 's/^"\+//; s/"\+$//;'
-                )
-                echo "processed_result=$processed_result" >> $GITHUB_OUTPUT
+              | map(@json)
+              | join("\n")' \
+            | sed 's/^"\+//; s/"\+$//;'
+          )
+          echo "processed_result=$processed_result" >> $GITHUB_OUTPUT
   slack-send-log:
     needs: get-waf-log
     runs-on: ubuntu-latest
@@ -132,4 +132,19 @@ jobs:
         run: |
           logs=${{ needs.get-waf-log.outputs.waf-log }}
           message="*[Tiếng Việt]*\nTitle Tiếng Việt TrieuLV\n\n*[English]*\nTittle English TrieuLV\n\n*[Logs - ${{ github.event.inputs.env }}]*\n\`\`\`json\n$logs\n\`\`\`"
-          curl -X POST -H 'Content-type: application/json' --data "$message" "$SLACK_WEBHOOK_URL_DEV"
+          echo "$message" > slack_message.txt
+      - name: Send message to Slack via webhook and check status
+        id: send_slack
+        run: |
+          payload=$(jq -Rs '{text: .}' < slack_message.txt)
+          status_code=$(curl -s -o response.txt -w "%{http_code}" -X POST -H 'Content-type: application/json' --data "$payload" ${{ secrets.SLACK_WEBHOOK_URL_DEV }})
+          echo "status_code=$status_code" >> $GITHUB_OUTPUT
+      - name: Check Slack message status
+        run: |
+          if [[ "${{ steps.send_slack.outputs.status_code }}" != "200" ]]; then
+            echo "Slack message sending failed with status code: ${{ steps.send_slack.outputs.status_code }}"
+            cat response.txt
+            exit 1
+          else
+            echo "Slack message sent successfully."
+          fi
